spring:
  application:
    name: oauth2-server
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/oauth2_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#    hikari:
#      minimum-idle: 5
#      idle-timeout: 600000
#      maximum-pool-size: 10
#      auto-commit: true
#      pool-name: MyHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1

server:
  port: 8081